<Root>:
    size:150,50
    Label:
        center_x: root.center_x
        center_y:root.height-10
        orientation: 'vertical'
        text: "Enter your name"

    TextInput:
        size: 200,30
        center_y: root.height/2
        center_x: root.center_x
        id:form

    Label:
        text: 'Hello!'
        center_x: root.center_x
        id: field

    Button:
        size: 100,30
        text: "ok"
        on_press: field.text = 'Hello, %s!' % (form.text)