<Separator>:
    canvas:
        Rectangle:
            pos: 0, self.center_y - 5
            size: self.width, 10

<Root>:
#
    orientation: 'vertical'
    MyGrid:
        Label:
            text: 'This is parent'
    Separator
    MyChild:
        Label:
            text: 'This is child'
    Separator
    SecChild:
        Label:
            text: 'This is second child'
    Separator
    FloatLayout:
        AnchorLayout:
            anchor_y : "bottom"
            anchor_x: "left"
            BoxLayout:
                orientation : "horizontal"
                spacing: 10
                size_hint: 0.4,0.1
                Button:
                    id : "_bfr"
                    text : "<-----"
#    Separator